import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { debts, payees, accounts } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { PageHeader } from '@/components/page-header'
import { formatCurrency } from '@/lib/format'
import { Archive, ArchiveRestore, Plus, HandCoins } from 'lucide-react'

const today = () => new Date().toISOString().slice(0, 10)
const field = 'w-full border rounded p-2 bg-background text-sm'
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div> }
function Summary({ title, items }: { title: string; items: any[] }) { const total = items.reduce((n, d) => n + Number(d.balance), 0); const currency = items[0]?.currency ?? 'TRY'; return <div className="bg-card border rounded-xl p-5"><div className="flex items-center gap-2 text-muted-foreground"><HandCoins size={18}/>{title}</div><p className="text-2xl font-bold mt-2">{formatCurrency(total, currency)}</p><p className="text-sm text-muted-foreground">{items.length} open position{items.length === 1 ? '' : 's'}</p></div> }

export default function DebtsPage() {
  const qc = useQueryClient(); const [createOpen, setCreateOpen] = useState(false); const [payId, setPayId] = useState<string | null>(null); const [detailId, setDetailId] = useState<string | null>(null); const [search, setSearch] = useState(''); const [archived, setArchived] = useState(false)
  const { data: list = [] } = useQuery({ queryKey: ['debts', search, archived], queryFn: () => debts.list({ search: search || undefined, archived }) }); const { data: people = [] } = useQuery({ queryKey: ['payees'], queryFn: payees.list }); const { data: accountList = [] } = useQuery({ queryKey: ['accounts'], queryFn: () => accounts.list() })
  const refresh = () => qc.invalidateQueries({ queryKey: ['debts'] }); const create = useMutation({ mutationFn: debts.create, onSuccess: () => { refresh(); setCreateOpen(false) } }); const pay = useMutation({ mutationFn: ({ id, data }: any) => debts.pay(id, data), onSuccess: () => { refresh(); setPayId(null) } }); const archive = useMutation({ mutationFn: ({ id, is_archived }: { id: string; is_archived: boolean }) => debts.update(id, { is_archived }), onSuccess: refresh }); const edit = useMutation({ mutationFn: ({ id, data }: { id: string; data: Record<string, unknown> }) => debts.update(id, data), onSuccess: () => { refresh(); setDetailId(null) } })
  const open = list.filter(d => d.balance > 0); const selected = list.find(d => d.id === payId); const detail = list.find(d => d.id === detailId)
  const submit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); create.mutate({ account_id: f.get('account_id'), payee_id: f.get('payee_id'), direction: f.get('direction'), description: f.get('description'), principal: Number(f.get('principal')), currency: f.get('currency'), opened_on: f.get('opened_on'), due_on: f.get('due_on') || null, notes: f.get('notes') || null, annual_interest_rate: f.get('annual_interest_rate') ? Number(f.get('annual_interest_rate')) : null, interest_start_on: f.get('interest_start_on') || null }) }
  return <div className="space-y-6"><PageHeader section="Finance" title="Debts" action={<Button onClick={() => setCreateOpen(true)}><Plus size={16}/> Add debt</Button>}/><p className="text-sm text-muted-foreground -mt-4">Receivables are assets; payables are liabilities. Equity = assets − liabilities.</p><div className="flex gap-2"><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search debts or payees"/><Button variant="outline" onClick={() => setArchived(!archived)}>{archived ? <ArchiveRestore size={16}/> : <Archive size={16}/>} {archived ? 'Open debts' : 'Archived'}</Button></div><div className="grid md:grid-cols-2 gap-4"><Summary title="Owed to you" items={open.filter(d => d.direction === 'receivable')}/><Summary title="You owe" items={open.filter(d => d.direction === 'payable')}/></div><div className="bg-card border rounded-xl overflow-hidden">{open.map(d => <div key={d.id} className="p-4 border-b flex justify-between gap-3"><div><button className="font-semibold hover:underline text-left" onClick={() => setDetailId(d.id)}>{d.description}</button><div className="text-sm text-muted-foreground">{d.payee_name} · {d.direction === 'receivable' ? 'owes you' : 'you owe'} · principal {formatCurrency(d.principal_balance, d.currency)}{d.accrued_interest > 0 && ` + interest ${formatCurrency(d.accrued_interest, d.currency)}`}</div></div><div className="text-right"><b>{formatCurrency(d.balance, d.currency)}</b><Button variant="outline" size="sm" className="ml-3" disabled={archived} onClick={() => setPayId(d.id)}>Record payment</Button><Button variant="ghost" size="sm" className="ml-1" onClick={() => archive.mutate({ id: d.id, is_archived: !archived })}>{archived ? 'Restore' : 'Archive'}</Button></div></div>)}{!open.length && <p className="p-8 text-center text-muted-foreground">No debts found.</p>}</div>
    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>Add debt</DialogTitle></DialogHeader><form className="space-y-3" onSubmit={submit}><Field label="Cash account"><select name="account_id" className={field} required><option value="">Select account</option>{accountList.map(a => <option value={a.id} key={a.id}>{a.name} ({a.currency})</option>)}</select></Field><Field label="Person or payee"><select name="payee_id" className={field} required><option value="">Select payee</option>{people.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></Field><Field label="Direction"><select name="direction" className={field}><option value="receivable">They owe me</option><option value="payable">I owe them</option></select></Field><Field label="Description"><Input name="description" required/></Field><div className="grid grid-cols-2 gap-3"><Field label="Principal amount"><Input name="principal" type="number" min="0" step="0.01" required/></Field><Field label="Currency"><Input name="currency" defaultValue="TRY" maxLength={3} required/></Field></div><Field label="Opening date"><Input name="opened_on" type="date" defaultValue={today()}/></Field><Field label="Due date (optional)"><Input name="due_on" type="date"/></Field><Field label="Annual interest rate (%)"><Input name="annual_interest_rate" type="number" min="0" step="0.01" placeholder="No interest"/></Field><Field label="Interest starts on (optional)"><Input name="interest_start_on" type="date"/></Field><Field label="Notes"><textarea name="notes" rows={3} className={field}/></Field><Button type="submit" className="w-full">Save debt and cash transaction</Button></form></DialogContent></Dialog>
    <Dialog open={!!payId} onOpenChange={() => setPayId(null)}><DialogContent><DialogHeader><DialogTitle>Record repayment</DialogTitle></DialogHeader><form className="space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); pay.mutate({ id: payId, data: { account_id: f.get('account_id'), amount: Number(f.get('amount')), paid_on: f.get('paid_on'), notes: f.get('notes') || null } }) }}><p>{selected?.description} — remaining {selected && formatCurrency(selected.balance, selected.currency)}</p><Field label="Cash account"><select name="account_id" className={field} required><option value="">Select account</option>{accountList.map(a => <option value={a.id} key={a.id}>{a.name} ({a.currency})</option>)}</select></Field><Field label="Payment amount"><Input name="amount" type="number" min="0.01" step="0.01" max={selected?.balance}/></Field><Field label="Payment date"><Input name="paid_on" type="date" defaultValue={today()}/></Field><Field label="Notes"><textarea name="notes" rows={3} className={field}/></Field><Button type="submit" className="w-full">Record payment and cash transaction</Button></form></DialogContent></Dialog>
    <Dialog open={!!detailId} onOpenChange={() => setDetailId(null)}><DialogContent><DialogHeader><DialogTitle>{detail?.description ?? 'Debt details'}</DialogTitle></DialogHeader>{detail && <form className="space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); edit.mutate({ id: detail.id, data: { description: f.get('description'), payee_id: f.get('payee_id'), account_id: f.get('account_id'), principal: Number(f.get('principal')), opened_on: f.get('opened_on'), due_on: f.get('due_on') || null, annual_interest_rate: f.get('annual_interest_rate') ? Number(f.get('annual_interest_rate')) : null, interest_start_on: f.get('interest_start_on') || null, notes: f.get('notes') || null } }) }}><Field label="Description"><Input name="description" defaultValue={detail.description} required/></Field><Field label="Payee"><select name="payee_id" defaultValue={detail.payee_id} className={field}>{people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Cash account"><select name="account_id" defaultValue={detail.account_id ?? ''} className={field}>{accountList.map(a => <option key={a.id} value={a.id}>{a.name} ({a.currency})</option>)}</select></Field><Field label="Principal amount"><Input name="principal" type="number" min="0" step="0.01" defaultValue={detail.principal}/></Field><Field label="Opening date"><Input name="opened_on" type="date" defaultValue={detail.opened_on}/></Field><Field label="Due date (optional)"><Input name="due_on" type="date" defaultValue={detail.due_on ?? ''}/></Field><Field label="Annual interest rate (%)"><Input name="annual_interest_rate" type="number" min="0" step="0.01" placeholder="No interest" defaultValue={detail.annual_interest_rate ?? ''}/></Field><Field label="Interest starts on (optional)"><Input name="interest_start_on" type="date" defaultValue={detail.interest_start_on ?? ''}/></Field><Field label="Notes"><textarea name="notes" defaultValue={detail.notes ?? ''} rows={3} className={field}/></Field><Button type="submit">Save changes</Button><div className="border-t pt-3 text-sm text-muted-foreground">Paid principal {formatCurrency(detail.principal_paid, detail.currency)} · Paid interest {formatCurrency(detail.interest_paid, detail.currency)} · Accrued interest {formatCurrency(detail.accrued_interest, detail.currency)}</div></form>}</DialogContent></Dialog></div>
}
